from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration, PythonExpression
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('verbose', default_value='false'),
        DeclareLaunchArgument('display', default_value='false'),
        DeclareLaunchArgument('input_mode', default_value='pointcloud',
            description='Input mode: "pointcloud" (organized colored PointCloud2) or "rgbd" (separate RGB + Depth images)'),
        DeclareLaunchArgument('cloud_topic', default_value='/bleu_tracker/points_world/full_point_cloud',
            description='PointCloud2 topic (used when input_mode=pointcloud)'),
        DeclareLaunchArgument('image_topic', default_value='/camera/color/image_raw',
            description='RGB image topic (used when input_mode=rgbd)'),
        DeclareLaunchArgument('depth_topic', default_value='/camera/aligned_depth_to_color/image_raw',
            description='Depth image topic (used when input_mode=rgbd)'),
        DeclareLaunchArgument('camera_info_topic', default_value='/camera/aligned_depth_to_color/camera_info',
            description='CameraInfo topic for intrinsics (used when input_mode=rgbd)'),
        DeclareLaunchArgument('depth_scale', default_value='0.001',
            description='Depth pixel value to meters scale factor (used when input_mode=rgbd)'),
        DeclareLaunchArgument('publish_tf', default_value='false'),
        DeclareLaunchArgument('tag_frame_prefix', default_value='apriltag',
            description='Prefix for per-tag TF child frames (e.g. apriltag_0, apriltag_1)'),
        DeclareLaunchArgument('publishing_frame', default_value='',
            description='If set, transform poses from camera frame to this frame before publishing. If empty, publish in camera frame.'),
        DeclareLaunchArgument('transform_timeout', default_value='0.1',
            description='Timeout in seconds for TF lookup when publishing_frame is set'),
        DeclareLaunchArgument('min_decision_margin', default_value='0.0',
            description='Minimum decision margin for AprilTag detection filtering (0.0 = no filtering)'),
        DeclareLaunchArgument('fix_axis', default_value='',
            description='Fix tag axis to parent frame axis: "tag_axis:frame_axis" e.g. "x:-z", "y:z" or legacy "z" (= "x:z"). Empty = disabled'),
        DeclareLaunchArgument('pose_mode', default_value='depth',
            description='Pose estimation mode: "depth" (RANSAC + depth) or "intrinsics" (classic apriltag from camera intrinsics)'),
        DeclareLaunchArgument('tag_size', default_value='0.16',
            description='Tag side length in meters (used when pose_mode=intrinsics)'),
        DeclareLaunchArgument('debug', default_value='false',
            description='Enable debug publishers (point cloud + segmentation image of detected tags)'),
        DeclareLaunchArgument('enable_apriltag_to_box', default_value='false',
            description='Launch apriltag_to_box node to convert tag pose to box obstacle'),
        DeclareLaunchArgument('apriltag_to_box_tag_id', default_value='23',
            description='AprilTag ID to use for box obstacle'),
        DeclareLaunchArgument('box_pose_topic', default_value='/g1pilot/box_pose',
            description='Output topic for box obstacle marker'),
        DeclareLaunchArgument('box_publishing_frame', default_value='',
            description='Frame to transform box marker into (empty = keep input frame)'),
        DeclareLaunchArgument('box_extents', default_value='0.02,0.0,1.09,0.30,0.25,0.56',
            description='Box extents: x_minus,x_plus,y_minus,y_plus,z_minus,z_plus (meters)'),
        Node(
            package='apriltag_pose',
            executable='apriltag_pose',
            name='apriltag_pose',
            output='screen',
            parameters=[{
                'verbose': LaunchConfiguration('verbose'),
                'display': LaunchConfiguration('display'),
                'input_mode': LaunchConfiguration('input_mode'),
                'cloud_topic': LaunchConfiguration('cloud_topic'),
                'image_topic': LaunchConfiguration('image_topic'),
                'depth_topic': LaunchConfiguration('depth_topic'),
                'camera_info_topic': LaunchConfiguration('camera_info_topic'),
                'depth_scale': LaunchConfiguration('depth_scale'),
                'publish_tf': LaunchConfiguration('publish_tf'),
                'tag_frame_prefix': LaunchConfiguration('tag_frame_prefix'),
                'publishing_frame': LaunchConfiguration('publishing_frame'),
                'transform_timeout': LaunchConfiguration('transform_timeout'),
                'min_decision_margin': LaunchConfiguration('min_decision_margin'),
                'fix_axis': LaunchConfiguration('fix_axis'),
                'pose_mode': LaunchConfiguration('pose_mode'),
                'tag_size': LaunchConfiguration('tag_size'),
                'debug': LaunchConfiguration('debug'),
            }],
        ),
        Node(
            condition=IfCondition(LaunchConfiguration('enable_apriltag_to_box')),
            package='apriltag_pose',
            executable='apriltag_to_box.py',
            name='apriltag_to_box',
            output='screen',
            parameters=[{
                'apriltag_pose_topic': PythonExpression([
                    "'apriltag_pose/pose_tag_' + '",
                    LaunchConfiguration('apriltag_to_box_tag_id'),
                    "'",
                ]),
                'box_topic': LaunchConfiguration('box_pose_topic'),
                'publishing_frame': LaunchConfiguration('box_publishing_frame'),
                'box_extents': LaunchConfiguration('box_extents'),
            }],
        ),
    ])
